server:
  servlet:
    context-path: /ssmapp
  port: 8800

spring:
  datasource:
    # ?serverTimezone=GMT%2B8 ：解决mysql时区乱码问题
    url: jdbc:mysql://localhost:3306/appinfodb?serverTimezone=GMT%2B8
    username: root
    password: 6868999

  servlet:
    multipart:
      enabled: true
      location: E:/temp




mybatis:
  # 包名格式为 xxx.yyy.zzz
  type-aliases-package: com.xlyd.springboot.app_platform.entity
  # mapper files location
  mapper-locations: classpath:com/xlyd/springboot/app_platform/dao/*Mapper.xml
  # mybatis config
  configuration:
    jdbc-type-for-null: null
    auto-mapping-behavior: full

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true

logging:
  level:
    root:
      INFO