server:
  servlet:
    context-path: /ssmapp



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 6868999



mybatis:
  type-aliases-package: com.xlyd.springboot.app_platform.entity
  # mapper files location
  mapper-locations: com/xlyd/springboot/app_platform/dao/*Mapper.xml
  # mybatis config
  configuration:
    jdbc-type-for-null: null
    auto-mapping-behavior: full


