server:
  servlet:
    context-path: /ssmapp

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 6868999



mybatis:
  type-aliases-package: com.xlyd.springboot.app_platform.entity
  # mapper files location
  mapper-locations: com/xlyd/springboot/app_platform/dao/*Mapper.xml
  # mybatis config
  configuration:
    jdbc-type-for-null: null
    auto-mapping-behavior: full

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true



---
spring:
  profiles: prod
  thymeleaf:
    cache: true

logging:
  level:
    root:
      WARNING
    org.spring.security:
      ERROR
---
spring:
  profiles: dev
  thymeleaf:
    cache: false

logging:
  level:
    root:
      DEBUG