spring:
  application:
    name: eureka-ha
server:
  port: 8761
  
eureka:
  instance:
     # 设置eureka实例名称，与配置文件的变量为主
    hostname: eureka1 
     # 设置服务注册中心地址，指向另一个注册中心  
  client:
    service-url: {
      defaultZone: "http://eureka2:8761/eureka/",
      
    }  
    
  server:
          # 关闭自我保护
    enable-self-preservation: false
          # 注册中心移除服务的时间间隔：毫秒
    eviction-interval-timer-in-ms: 60000







