server:
  port: 8080
  servlet:
    context-path: /test


# date to json
spring: 
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
      
  devtools:
    restart:
      enabled: true
      
  thymeleaf:
    cache: false 
      
      
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 6868999
  

logging:
  level: 
    ROOT: INFO



      

