
spring:
  application:
    name: eureka-client
server:
  port: 9090

eureka:
  client:
    service-url:
    #服务注册中心地址
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8761/eureka/

    
